MAINT: Create FUNDING.yml
RocketPy-Team/RocketPy pull request #213
Opened 2022-08-24 02:38 UTC by Gui-FernandesBR

## Pull request type

- [X] ReadMe, Docs and GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [X] Spelling has been verified
  - [X] Code docs are working correctly 

- Code base maintenance (refactoring, formatting, renaming):

## What is the new behavior?

Now adding a new Sponsors Button on our main page

## Does this introduce a breaking change?

- [X] No

## Other information

In the future we probably may publish sponsors logos here

2022-08-24 02:51 UTC, giovaniceotto commented
Should we create other sponsor accounts, such as Patreon?

2022-08-24 02:52 UTC, giovaniceotto requested changes
Please remove the unused model platforms to prevent syntax erros in the yaml file.

2022-08-24 02:52 UTC, giovaniceotto commented on .github/FUNDING.yml
> +custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
```suggestion
```

2022-08-24 03:02 UTC, giovaniceotto approved these changes

2022-08-24 03:03 UTC, merged

2022-08-25 01:11 UTC, Gui-FernandesBR commented
> Should we create other sponsor accounts, such as Patreon?

Sure thing! Let's note this for later