Enh/liquid motors tank inertia
RocketPy-Team/RocketPy pull request #299
Opened 2022-11-16 01:31 UTC by phmbressan

## Pull request type

Please check the type of change your PR introduces:

- [x] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

- Code base additions (for bug fixes / features):

  - [x] Tests for the changes have been added
  - [ ] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [ ] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

There is no support for non flat cap inertia evaluation nor the tank gaseous volume.

## What is the new behavior?

Expand inertia evaluation for Tanks. The new behavior includes spherical cap inertia calculations and the gaseous portion is taken into account.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2022-11-18 16:45 UTC, giovaniceotto commented
Currently working on this review but haven't finished yet. Expect to finish it by today.

2022-11-19 03:43 UTC, giovaniceotto requested changes
Almost there! Implementation is looking awesome. I just made a small number of suggestions.

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        pass
Consider removing unnecessary lines.

```suggestion
```

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        )
Should we add error handling to deal with non-existent cap types?

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        gases at each part of the tank (body and caps) as well as its masses.
```suggestion
        gases at each part of the tank (body and caps) as well as their masses.
```

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        time.
TODO: Specify relative to which point is the center of mass calculated (coordinate system orientation and origin).

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        based on the volume distributions.
TODO: Make it clear relative to which point are the centroids calculated (coordinate system orientation and origin).

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +        time.
TODO: make it clear relative to which origin and axes (coordinate system) is this being calculated.

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/Tank.py
> +            )
No real change, just a suggestion to make things more symmetric.

```suggestion
            bottomCapMassBalance = (
                self.bottomCapLiquidMass * self.bottomCapLiquidCentroid
                + self.bottomCapGasMass * self.bottomCapGasCentroid
            )
```

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/TankGeometry.py
> +                - "upwards": propellant is filled with the convex site facing down, as in
> 
```suggestion
                - "upwards": propellant is filled with the convex side facing down, as in
```

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/TankGeometry.py
> +                - "downwards": propellant is filled with the concave site facing down, as
```suggestion
                - "downwards": propellant is filled with the concave side facing down, as
```

2022-11-19 03:43 UTC, giovaniceotto commented on rocketpy/motors/TankGeometry.py
> +            The default is "upwards", and will be used if the user commits a typing error.
Seems dangerous to do this. If the user writes "down", it is use "upwards". I believe implementing error handling would be more appropriate here.

2022-11-19 11:23 UTC, phmbressan commented
Thank you for the review, great points were made! I will analyse and implement the suggested changes today.

2022-11-21 18:44 UTC, giovaniceotto approved these changes

2022-11-21 18:45 UTC, merged