HOTFIX: v1.1.1
RocketPy-Team/RocketPy pull request #483
Opened 2023-11-23 15:25 UTC by MateusStano

## Fixed

https://github.com/RocketPy-Team/RocketPy/pull/479:
- Opposite static margin bug, which affected all rockets defined using a nose_to_tail coordinate system, causing positive static margins to become negative and negative ones to become positive. Note: this bug did not lead to any issues in terms of the trajectory simulation itself.

https://github.com/RocketPy-Team/RocketPy/pull/478:
- Fixed Bug in 2D .csv-Based Functions for Proper Interpolation Handling and Added Relevant Test Coverage

https://github.com/RocketPy-Team/RocketPy/pull/476:
- Corrected Function.compose extrapolation.
- Added overfill validation in MassBasedTank.fluid_volume.
- Introduced assertion in test_mass_based_tank to prevent future errors in fluid_volume.

2023-11-23 15:31 UTC, Gui-FernandesBR requested changes
Thank you @MateusStano !!

2 changes that we still need to do before merging:
- Update the CHANGELOG file.
- Re-run the SEBLM notebook to update the static margin plot. See:

![image](https://github.com/RocketPy-Team/RocketPy/assets/63590233/6083a3b4-34bb-4122-8476-2a126b5d044e)

2023-11-23 15:37 UTC, Gui-FernandesBR commented
We should have more tests for the tanks, not all the lines are being covered right now, as reported by the codecov

2023-11-23 15:50 UTC, Gui-FernandesBR commented
This one solves #482

2023-11-23 15:52 UTC, Gui-FernandesBR approved these changes
Great one!

2023-11-24 20:42 UTC, phmbressan approved these changes
Great fixes. I just noticed a small assertion mistake and will commit a fix.

2023-11-24 20:42 UTC, phmbressan commented on tests/test_tank.py
> +    assert (real_tank_lox.gas_height <= real_tank_lox.geometry.total_volume).all
This line is wrong, it should be 


```suggestion
    assert (real_tank_lox.gas_height <= real_tank_lox.geometry.top).all
```

2023-11-24 22:06 UTC, merged