Splitting conftest.py into several smaller files.
RocketPy-Team/RocketPy pull request #556
Opened 2024-02-13 21:52 UTC by lucasfourier

## Pull request type

- [ ] Code changes (bugfix, features)
- [X] Code maintenance (refactoring, formatting, tests)
- [ ] ReadMe, Docs and GitHub updates
- [ ] Other (please describe):

## Checklist

- [ ] Tests for the changes have been added (if needed)
- [ ] Docs have been reviewed and added / updated
- [ ] Lint (`black rocketpy/ tests/`) has passed locally 
- [X] All tests (`pytest tests -m slow --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Current behavior

Currently, conftest.py is unique and top level within the tests directory. However, as observed by @Gui-FernandesBR in #447, the file was getting too big to be properly maintained. 

## New behavior

Several .py modules were created in order to split the fixtures into modules which results in easier maintenance and proper organization.

## Breaking change

- [ ] Yes
- [X] No

## Additional information

A bit more info regarding this can be found here: 
https://stackoverflow.com/questions/27064004/splitting-a-conftest-py-file-into-several-smaller-conftest-like-parts

2024-02-13 22:30 UTC, Gui-FernandesBR requested changes
Good work, the new structure is just way better than the current one. more robust and scalable.

Please discuss on the comments I've added and let me know if there's something not so clear.

Can you apply black before commiting? Out Makefile has been updated recently if you wanna use the `make black` command.

Also, can you confirm the slow tests are passing locally?

Once again, good work here!

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## AeroSurfaces
This is useless

```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## Parachutes
```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## Flights
```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## Dimensionless motors and rockets
```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## Environment
```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/conftest.py
>  ## Functions
```suggestion
```

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/fixtures/hybrid/__init__.py
I don't think having a `tests/fixtures/hybrid` module is something good.
It would be more clear to me if we followed the same structure as in the `rocketpy` package.

My suggestion:

```bash
fixtures
    - ...
    - motor
         - __init__.py
         -  hybrid_fixtures.py
         - solid_motor_fixtures.py
         - liquid_fixtures.py
```

This way all the motor fixtures are contained inside the `motors` folder, just like in the main rocketpy package.

2024-02-13 22:30 UTC, Gui-FernandesBR commented on tests/fixtures/motor/motor_fixtures.py
> +def generic_motor():
GenericMotor is a different class than SolidMotor. I would separate that as well.

consider renaming motor_fixtures.py to solid_motor_fixtures.py 

You can use git rename for that.

2024-02-14 00:36 UTC, lucasfourier commented on tests/fixtures/hybrid/__init__.py
Agree 100%

2024-02-14 07:29 UTC, Gui-FernandesBR requested changes
Thank you again for your effort, I really appreciate it, @lucasfourier .

I've added a few more comments on what I think is not ideal yet, could you check it out please?

2024-02-14 07:29 UTC, Gui-FernandesBR commented on tests/fixtures/motor/motor_fixtures.py
This `tests/fixtures/motor/motor_fixtures.py` file is duplicated, it doesn't make sense to be here.
You can simply delete it and then commit the deletion.

2024-02-14 07:29 UTC, Gui-FernandesBR commented on tests/fixtures/hybrid/hybrid_fixtures.py
> +
I think this is in the wrong place, it is duplicated from the liquid_motor_fixtures.py file.  Am I right? Can you please delete these lines if yes, please?

2024-02-14 07:29 UTC, Gui-FernandesBR commented on tests/fixtures/motor/liquid_fixtures.py
Could you consider creating a `tests/fixtures/motor/tanks_fixtures.py` with all the required tanks?
I think this would alleviate the liquid_fixtures.py file.

2024-02-18 22:17 UTC, Gui-FernandesBR commented on tests/fixtures/motor/motor_fixtures.py
@lucasfourier can you take a look at this please?

2024-02-18 23:04 UTC, Gui-FernandesBR approved these changes
Great PR, thank you so much for your contribution, @lucasfourier !!

Tests are now more organized and faster.

You can merge this PR once the tests are all green in github actions. Also, please feel free to close the issue associated with this PR.

2024-02-19 00:56 UTC, merged