BUG: Motor method 'export_eng' for liquid motors bug fix. (solves #473)
RocketPy-Team/RocketPy pull request #559
Opened 2024-02-20 17:47 UTC by lucasfourier

## Pull request type

- [X] Code changes (bugfix, features)
- [X] Code maintenance (refactoring, formatting, tests)
- [ ] ReadMe, Docs and GitHub updates
- [ ] Other (please describe):

## Checklist

- [ ] Tests for the changes have been added (if needed)
- [X] Docs have been reviewed and added / updated
- [X] Lint (`black rocketpy/ tests/`) has passed locally 
- [X] All tests (`pytest tests -m slow --runslow`) have passed locally
- [ ] `CHANGELOG.md` has been updated (if relevant)

## Current behavior

As described in #473, 'export_eng' method does not work for liquid motors since it does not have grain related attributes.

## New behavior

The Motor method 'export_eng' now works for liquid motors and the .eng file is created. For liquid motors, the first two parameters written to the file are now zeros, since those are grain related attributes.

## Breaking change

- [ ] Yes
- [X] No

## Additional information

Below is the '.eng' file generated for the liquid motor defined in the SEB_liquid_motor.ipynb notebook.

![image](https://github.com/RocketPy-Team/RocketPy/assets/69172945/139ce577-28a1-4e08-9055-a6553e0df1d4)

2024-02-20 17:50 UTC, lucasfourier commented
I'd like to add that Issue #473 requests the implementation of tests. However, I'd like to request permission to not write tests for this method for now. My plan is to refactor the unit tests for the liquid_motor module later today, and I intend to include the tests for this method as part of that refactor.

2024-02-20 18:02 UTC, Gui-FernandesBR commented
.eng files documentation: https://www.thrustcurve.org/info/raspformat.html

Saving that for reference.

2024-02-22 21:31 UTC, Gui-FernandesBR reviewed
I know the code works, but I think there is a little code repetition that perhaps could be avoid, thus improving readability.

I will add a code suggestion here. I know it is also changing some other stuffs like the "with context" and adopting the f-strings instead of .format(), but I hope you can understand it. Feel free to accept the suggestions, while in this very same PR or in other.

```python
    def export_eng(self, file_name, motor_name):
        """Exports thrust curve data points and motor description to
        .eng file format. A description of the format can be found
        here: http://www.thrustcurve.org/raspformat.shtml

        Parameters
        ----------
        file_name : string
            Name of the .eng file to be exported. E.g. 'test.eng'
        motor_name : string
            Name given to motor. Will appear in the description of the
            .eng file. E.g. 'Mandioca'

        Returns
        -------
        None
        """
        # Open file
        with open(file_name, "w") as file:
            # Write first line
            def get_attr_value(obj, attr_name, multiplier=1):
                return multiplier * getattr(obj, attr_name, 0)

            grain_outer_radius = get_attr_value(self, "grain_outer_radius", 2000)
            grain_number = get_attr_value(self, "grain_number", 1000)
            grain_initial_height = get_attr_value(self, "grain_initial_height")
            grain_separation = get_attr_value(self, "grain_separation")

            grain_total = grain_number * (grain_initial_height + grain_separation)

            if grain_outer_radius == 0 or grain_total == 0:
                warnings.warn(
                    "The motor object doesn't have some grain-related attributes. "
                    "Using zeros to write to file."
                )

            file.write(
                f"{motor_name} {grain_outer_radius:3.1f} {grain_total:3.1f} 0 "
                f"{self.propellant_initial_mass:2.3} "
                f"{self.propellant_initial_mass:2.3} RocketPy\n"
            )

            # Write thrust curve data points
            for time, thrust in self.thrust.source[1:-1, :]:
                file.write(f"{time:.4f} {thrust:.3f}\n")

            # Write last line
            file.write(f"{self.thrust.source[-1, 0]:.4f} {0:.3f}\n")

        return None
```

2024-02-24 20:26 UTC, lucasfourier commented
@Gui-FernandesBR Much better, thanks. Committed your solution

2024-02-24 22:36 UTC, Gui-FernandesBR reviewed
Nice, well done @lucasfourier !!

Can you please update the CHANGELOG.md file with this PR?
It is important since it makes it easier for users and contributors to see precisely what changes have been made between each version of the project.

See https://keepachangelog.com/en/1.0.0/

2024-02-24 22:48 UTC, lucasfourier commented
Done it

2024-02-24 23:04 UTC, Gui-FernandesBR requested changes
Thanks for updating the CHANGELOG, but it was wrong though. 

Please add your PR to the `[Unreleased] - yyyy-mm-dd` section, under the Fixed.

The v1.2.0 (where you added) is already released.

2024-02-24 23:13 UTC, lucasfourier commented
Fixed it

2024-02-25 00:18 UTC, Gui-FernandesBR requested changes
Still requiring changes on the CHANGELOG. Please take a look at other sections of the file so you can keep the same pattern

2024-02-25 00:18 UTC, Gui-FernandesBR commented on CHANGELOG.md
This is better:

```markdown
## [Unreleased] - yyyy-mm-dd
<!-- These are the changes that were not release yet, please add them correctly.
  Attention: The newest changes should be on top -->

### Added

### Changed

### Fixed
- BUG: export_eng 'Motor' method would not work for liquid motors. [#559](https://github.com/RocketPy-Team/RocketPy/pull/559)
```

2024-02-25 00:50 UTC, Gui-FernandesBR approved these changes

2024-02-26 00:53 UTC, lucasfourier commented on CHANGELOG.md
Got it!

2024-02-26 00:58 UTC, Gui-FernandesBR approved these changes

2024-02-26 01:08 UTC, merged