DOC: Lince (Team STAR) 2023 flight sim
RocketPy-Team/RocketPy pull request #752
Opened 2024-12-11 19:47 UTC by LUCKIN13

## Pull request type

- [x] ReadMe, Docs and GitHub updates

## Checklist

- [x] Docs have been reviewed and added / updated
- [ ] Lint (`black rocketpy/ tests/`) has passed locally 
- [ ] All tests (`pytest tests -m slow --runslow`) have passed locally
- [x] `CHANGELOG.md` has been updated (if relevant)

## Additional information
Unfortunately I couldn't find any GNSS flight data from the payload. However, this is still a really good example of a simulation model with deployable payload.

2024-12-11 19:58 UTC, Gui-FernandesBR commented on docs/examples/lince_flight_sim.ipynb
can you double check the plots in the `## Flight Simulation` section please?
Seems odd to me that both 3D plots look the same

2024-12-11 23:17 UTC, LUCKIN13 commented on docs/examples/lince_flight_sim.ipynb
Double checked all the parameters.  They are indeed pretty similar, but I did some tests and the difference makes sense according to the difference in weight and parachute cds.

2024-12-13 04:35 UTC, Gui-FernandesBR commented on data/weather/euroc_2023_fixed.nc
@LUCKIN13  why do you need this file? Isn't there another .nc file for euroc 2023?

2024-12-13 04:37 UTC, Gui-FernandesBR reviewed
This plot isn't correct.
The flight should stop at the main deployment height.
You should set a max_time for the first flight object.

![image](https://github.com/user-attachments/assets/5e9ebd5b-467d-4445-b221-227adbe85edf)

Also, how did you generate the initial solution for other flights?

2024-12-13 04:38 UTC, Gui-FernandesBR requested changes
Also, please add this flight to the comparison plot on the index.rst file

2024-12-13 18:27 UTC, LUCKIN13 commented on data/weather/euroc_2023_fixed.nc
@Gui-FernandesBR unfortunately, the other file seems to have some kind of error. I noticed, while working on the other examples, that the wind velocities were around 100–200 m/s, which is unrealistic. I made a new request to Copernicus, and I’m considering updating all the EUROC 2023 examples to use the new file and deleting the older one (if it is no longer needed for anything else).

2024-12-13 18:28 UTC, LUCKIN13 commented
> Also, please add this flight to the comparison plot on the index.rst file

Sorry for forgetting that. Will do that asap

2024-12-13 18:36 UTC, Gui-FernandesBR commented on data/weather/euroc_2023_fixed.nc
Are other examples also wrong?

I don't like the name of the new file at all. We should either delete the older or the new file, keeping only one is the best approach.

2024-12-13 20:57 UTC, LUCKIN13 commented on data/weather/euroc_2023_fixed.nc
I was checking and looks like all the flight examples have wind speeds over 150 m/s. I gave that name knowing that would be temporary (either stick with the old one, or change)

2024-12-15 02:10 UTC, Gui-FernandesBR commented on docs/examples/lince_flight_sim.ipynb
Good.

2024-12-15 02:11 UTC, Gui-FernandesBR commented on data/weather/euroc_2023_fixed.nc
I think #735 solved that!

Btw we should create more acceptance tests in order to fix that.

2024-12-15 02:13 UTC, Gui-FernandesBR commented
@LUCKIN13 try to read my last commit, I think the #735 solved the problem with the wind speeds.
The problematic code was related to the environment class, not the .nc file, so I've deleted your new file and preserved only the old one.

2024-12-15 02:22 UTC, Gui-FernandesBR approved these changes
LGTM

2024-12-15 02:30 UTC, merged

2024-12-15 19:59 UTC, LUCKIN13 commented
> @LUCKIN13 try to read my last commit, I think the #735 solved the problem with the wind speeds. The problematic code was related to the environment class, not the .nc file, so I've deleted your new file and preserved only the old one.

Great! Makes sense, since all the other examples also add some problems. Thanks a lot for your help!